"""empty message

Revision ID: 65cad70dc2cf
Revises: 7f33a7d6871c
Create Date: 2020-03-04 22:43:44.445110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65cad70dc2cf'
down_revision = '7f33a7d6871c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothes_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clothes_type', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_status', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile')
    )
    op.create_table('clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('priceDay', sa.Float(), nullable=True),
    sa.Column('locale', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('avaliable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['clothes_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clothe_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clothes_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['clothes_id'], ['clothes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locator_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.Column('location_status', sa.Integer(), nullable=True),
    sa.Column('clothes_id', sa.Integer(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('avaliation_note', sa.Integer(), nullable=True),
    sa.Column('avaliation_text', sa.Text(length=500), nullable=True),
    sa.ForeignKeyConstraint(['clothes_id'], ['clothes.id'], ),
    sa.ForeignKeyConstraint(['location_status'], ['location_status.id'], ),
    sa.ForeignKeyConstraint(['locator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'profile', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'profile_id')
    op.drop_table('location')
    op.drop_table('clothe_images')
    op.drop_table('clothes')
    op.drop_table('profile')
    op.drop_table('location_status')
    op.drop_table('clothes_type')
    # ### end Alembic commands ###
